use sakila;

--------- List the number of films per category.--------------
select c.name, count(f.film_id) as no_Film
from category c 
join film_category fc using (category_id)
join film f using (film_id)
group by c.name
order by no_film desc;

-- --------Retrieve the store ID, city, and country for each store.-----------

select si.store_id as store_name, ci.city, co.country
from store si
left join address ad using (address_id)
join city ci using(city_id)
join country co using (country_id)
group by si.store_id,co.country,ci.city;

----------- Calculate the total revenue generated by each store in dollars.-------------

select c.store_id as store_num,sum(p.amount) as total_amount
from payment p 
join  customer c using (customer_id)
join store si using (store_id)
group by  c.store_id;

------------ Determine the average running time of films for each category.-------------
select c.name, avg(f.length) as avg_time_film
from category c
join film_category fc using(category_id)
join film f using (film_id)
group by c.name
order by avg_time_film desc;



